from django.urls import path

from chat.interfaces.api.views import (
	AdminConversationListAPIView,
	AdminMessageListAPIView,
	ChatSearchAPIView,
	ChatSettingsAPIView,
	ConversationDetailAPIView,
	ConversationDisbandAPIView,
	ConversationAttachmentMessageAPIView,
	ConversationHideAPIView,
	ConversationInviteAPIView,
	ConversationLeaveAPIView,
	ConversationMembersAPIView,
	ConversationMessagesAPIView,
	ConversationMuteMemberAPIView,
	MessageDeleteAPIView,
	MessageForwardAPIView,
	MessageRestoreDraftAPIView,
	MessageRevokeAPIView,
	ConversationPinAPIView,
	ConversationPreferenceAPIView,
	ConversationReadAPIView,
	ConversationRemoveMemberAPIView,
	ConversationTransferOwnerAPIView,
	ConversationUpdateMemberRoleAPIView,
	ConversationListAPIView,
	DirectConversationOpenAPIView,
	FriendDeleteAPIView,
	FriendListAPIView,
	FriendSettingAPIView,
	FriendRequestHandleAPIView,
	FriendRequestListCreateAPIView,
	GroupConfigAPIView,
	GroupInvitationApplyAPIView,
	GroupConversationCreateAPIView,
	GroupJoinRequestHandleAPIView,
	GroupJoinRequestListAPIView,
)

app_name = "chat"

urlpatterns = [
	path("friends/requests/", FriendRequestListCreateAPIView.as_view(), name="friend_requests"),
	path("friends/requests/<int:request_id>/handle/", FriendRequestHandleAPIView.as_view(), name="friend_request_handle"),
	path("friends/", FriendListAPIView.as_view(), name="friends"),
	path("friends/<int:friend_user_id>/delete/", FriendDeleteAPIView.as_view(), name="friend_delete"),
	path("friends/<int:friend_user_id>/settings/", FriendSettingAPIView.as_view(), name="friend_settings"),
	path("conversations/", ConversationListAPIView.as_view(), name="conversation_list"),
	path("conversations/direct/open/", DirectConversationOpenAPIView.as_view(), name="conversation_open_direct"),
	path("conversations/groups/", GroupConversationCreateAPIView.as_view(), name="conversation_create_group"),
	path("conversations/<int:conversation_id>/", ConversationDetailAPIView.as_view(), name="conversation_detail"),
	path("conversations/<int:conversation_id>/hide/", ConversationHideAPIView.as_view(), name="conversation_hide"),
	path("conversations/<int:conversation_id>/read/", ConversationReadAPIView.as_view(), name="conversation_read"),
	path("conversations/<int:conversation_id>/pin/", ConversationPinAPIView.as_view(), name="conversation_pin"),
	path("conversations/<int:conversation_id>/preferences/", ConversationPreferenceAPIView.as_view(), name="conversation_preferences"),
	path("conversations/<int:conversation_id>/messages/", ConversationMessagesAPIView.as_view(), name="conversation_messages"),
	path("conversations/<int:conversation_id>/attachments/", ConversationAttachmentMessageAPIView.as_view(), name="conversation_attachments"),
	path("messages/forward/", MessageForwardAPIView.as_view(), name="message_forward"),
	path("messages/<int:message_id>/delete/", MessageDeleteAPIView.as_view(), name="message_delete"),
	path("messages/<int:message_id>/revoke/", MessageRevokeAPIView.as_view(), name="message_revoke"),
	path("messages/<int:message_id>/restore-draft/", MessageRestoreDraftAPIView.as_view(), name="message_restore_draft"),
	path("conversations/<int:conversation_id>/members/", ConversationMembersAPIView.as_view(), name="conversation_members"),
	path("conversations/<int:conversation_id>/members/invite/", ConversationInviteAPIView.as_view(), name="conversation_member_invite"),
	path("group-invitations/apply/", GroupInvitationApplyAPIView.as_view(), name="group_invitation_apply"),
	path("conversations/<int:conversation_id>/leave/", ConversationLeaveAPIView.as_view(), name="conversation_leave"),
	path("conversations/<int:conversation_id>/transfer-owner/", ConversationTransferOwnerAPIView.as_view(), name="conversation_transfer_owner"),
	path("conversations/<int:conversation_id>/disband/", ConversationDisbandAPIView.as_view(), name="conversation_disband"),
	path("conversations/<int:conversation_id>/members/<int:user_id>/remove/", ConversationRemoveMemberAPIView.as_view(), name="conversation_member_remove"),
	path("conversations/<int:conversation_id>/members/<int:user_id>/role/", ConversationUpdateMemberRoleAPIView.as_view(), name="conversation_member_role"),
	path("conversations/<int:conversation_id>/members/<int:user_id>/mute/", ConversationMuteMemberAPIView.as_view(), name="conversation_member_mute"),
	path("conversations/<int:conversation_id>/group-config/", GroupConfigAPIView.as_view(), name="conversation_group_config"),
	path("group-join-requests/", GroupJoinRequestListAPIView.as_view(), name="group_join_requests"),
	path("group-join-requests/<int:request_id>/handle/", GroupJoinRequestHandleAPIView.as_view(), name="group_join_request_handle"),
	path("search/", ChatSearchAPIView.as_view(), name="chat_search"),
	path("settings/", ChatSettingsAPIView.as_view(), name="chat_settings"),
	path("admin/conversations/", AdminConversationListAPIView.as_view(), name="admin_conversations"),
	path("admin/messages/", AdminMessageListAPIView.as_view(), name="admin_messages"),
]