# Generated by Django 5.2 on 2026-04-08 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbot', '0005_uploadedfile_recycle_original_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('file_md5', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='文件MD5')),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='文件SHA256')),
                ('storage_backend', models.CharField(choices=[('local', '本地存储')], db_index=True, default='local', max_length=32, verbose_name='存储后端')),
                ('storage_key', models.CharField(db_index=True, max_length=500, verbose_name='存储键')),
                ('mime_type', models.CharField(blank=True, default='', max_length=255, verbose_name='MIME 类型')),
                ('media_type', models.CharField(choices=[('file', '文件'), ('image', '图片'), ('audio', '音频'), ('video', '视频'), ('avatar', '头像'), ('system', '系统')], db_index=True, default='file', max_length=32, verbose_name='媒体类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('extension', models.CharField(blank=True, default='', max_length=32, verbose_name='扩展名')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('extra_metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展元数据')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'asset',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ref_domain', models.CharField(choices=[('resource_center', '资源中心'), ('chat', '聊天'), ('user_profile', '用户资料'), ('system', '系统')], db_index=True, default='resource_center', max_length=32, verbose_name='引用域')),
                ('ref_type', models.CharField(choices=[('file', '文件'), ('directory', '目录'), ('avatar', '头像'), ('chat_attachment', '聊天附件')], db_index=True, default='file', max_length=32, verbose_name='引用类型')),
                ('ref_object_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='业务对象ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='显示名')),
                ('relative_path_cache', models.CharField(blank=True, default='', max_length=500, verbose_name='相对路径缓存')),
                ('status', models.CharField(choices=[('active', '正常'), ('recycled', '回收站'), ('deleted', '删除')], db_index=True, default='active', max_length=32, verbose_name='状态')),
                ('recycled_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='移入回收站时间')),
                ('visibility', models.CharField(choices=[('private', '私有'), ('conversation', '会话内'), ('public', '公开'), ('system', '系统')], db_index=True, default='private', max_length=32, verbose_name='可见性')),
                ('extra_metadata', models.JSONField(blank=True, default=dict, verbose_name='扩展元数据')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='bbot.asset', verbose_name='资产')),
                ('legacy_uploaded_file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_reference_compat', to='bbot.uploadedfile', verbose_name='兼容 UploadedFile')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_asset_references', to=settings.AUTH_USER_MODEL, verbose_name='引用归属用户')),
                ('parent_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bbot.assetreference', verbose_name='父引用')),
            ],
            options={
                'db_table': 'asset_reference',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['media_type', 'created_by'], name='asset_media_t_919618_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('storage_backend', 'storage_key'), name='uq_asset_storage_backend_key'),
        ),
        migrations.AddIndex(
            model_name='assetreference',
            index=models.Index(fields=['owner_user', 'parent_reference', 'status'], name='asset_refer_owner_u_baf05f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetreference',
            index=models.Index(fields=['ref_domain', 'ref_type', 'ref_object_id'], name='asset_refer_ref_dom_adc0be_idx'),
        ),
        migrations.AddIndex(
            model_name='assetreference',
            index=models.Index(fields=['asset', 'status'], name='asset_refer_asset_i_22f9e8_idx'),
        ),
    ]
