# Generated by Django 5.2 on 2026-03-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=64, verbose_name='业务分类')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_md5', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='文件MD5')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('relative_path', models.CharField(max_length=500, verbose_name='上传相对路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'db_table': 'hyself_uploaded_file',
                'ordering': ['-id'],
            },
        ),
    ]
