# Generated by Django 5.2 on 2026-03-31 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyself', '0002_uploadedfile_deleted_at_uploadedfile_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='original_name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='展示文件名'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_dir',
            field=models.BooleanField(default=False, verbose_name='是否目录'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hyself.uploadedfile', verbose_name='父目录'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='stored_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='存储文件名'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='business',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='业务分类(兼容字段)'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_md5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='文件MD5'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='relative_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='上传相对路径'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['created_by', 'parent'], name='uploaded_fi_created_3a1c45_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['created_by', 'is_dir'], name='uploaded_fi_created_323e0f_idx'),
        ),
    ]
