# Generated by Django 5.2 on 2026-04-24 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hyself", "0008_rename_asset_media_t_919618_idx_hyself_asse_media_t_0d4272_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAnnouncement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("title", models.CharField(max_length=255, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                ("published_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="发布时间")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_system_announcements", to=settings.AUTH_USER_MODEL, verbose_name="发布人")),
            ],
            options={
                "db_table": "hyself_system_announcement",
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.CharField(default="default", max_length=32, unique=True, verbose_name="单例键")),
                ("system_title", models.CharField(blank=True, default="", max_length=255, verbose_name="系统标题")),
                ("maintenance_enabled", models.BooleanField(db_index=True, default=False, verbose_name="是否启用系统维护")),
                ("maintenance_scheduled_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="维护开始时间")),
                ("maintenance_activated_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="维护实际激活时间")),
                ("maintenance_processed_at", models.DateTimeField(blank=True, default=None, null=True, verbose_name="维护动作处理时间")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_system_settings", to=settings.AUTH_USER_MODEL, verbose_name="最后操作人")),
            ],
            options={
                "db_table": "hyself_system_setting",
            },
        ),
        migrations.CreateModel(
            name="SystemAnnouncementRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="已读时间")),
                ("announcement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="read_records", to="hyself.systemannouncement", verbose_name="公告")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="system_announcement_reads", to=settings.AUTH_USER_MODEL, verbose_name="用户")),
            ],
            options={
                "db_table": "hyself_system_announcement_read",
            },
        ),
        migrations.AddConstraint(
            model_name="systemannouncementread",
            constraint=models.UniqueConstraint(fields=("announcement", "user"), name="uq_system_announcement_read_user"),
        ),
        migrations.AddIndex(
            model_name="systemannouncementread",
            index=models.Index(fields=["user", "read_at"], name="hyself_syst_user_id_f05c6c_idx"),
        ),
    ]